### ISSUE TITLE
Challenge: Ready for Orchestration

### ISSUE THREAD

**Issue by dsturgell** [atxryan/nwa-tech-summit#12]
- Use Azure Kubernetes Service to configure and create a Kubernetes cluster 
     - Confirm Kubectl get nodes 
- Integrate identity with AKS (AAD-pod-identity) 
- Deploy bluebell-nwa container from Challenge 1 to the Kubernetes cluster using appropriate
   namespaces 
     - Configure yaml w/ env vars 
     - Open aks URL from browser

**Comment by evillgenius75** [comment]
Added content for AAD Pod Identity and reviewed content already created.
