### ISSUE TITLE
Logistics: Pre-Hack Setup Test

### ISSUE THREAD

**Issue by dsturgell** [atxryan/nwa-tech-summit#21]
Test computers/setup prior to hack; identifying time to do with organizers

**Comment by dsturgell** [comment]
@atxryan  Do we have any specifics logistics needed for the hack?  Mics? Displays? Screens?  etc...

**Comment by dsturgell** [comment]
@atxryan Any specific request for demo/presentation setup?

**Comment by atxryan** [comment]
@dsturgell I'll have my HDMI-to-Minidisplay adapter with us. We should be good. Can't answer for sure on audio with knowing the space so we may have to project our voices. :-)

**Comment by dsturgell** [comment]
Checking on lavalier microphone
