### ISSUE TITLE
Logistics: Team Travel Details

### ISSUE THREAD

**Issue by dsturgell** [atxryan/nwa-tech-summit#23]
@bartr @atxryan @atxryan @dsturgell 

Please add your travel details below:
- Arrival Date
- Arrival Time

Working on scheduling time for us to walk thru site & of course a team dinner :)

**Comment by dsturgell** [comment]
Deanna:
Arrival Date: Monday, October 21st
Arrival Time: 3:45pm

**Comment by aflinchb** [comment]
Arrival Date: Monday, October 21st
Arrival Time: 9:52am

**Comment by bartr** [comment]
I'm not getting there until late :(

**Comment by dsturgell** [comment]
Ryan 
Arrival Date: Monday, October 21st
Time: Early AM
