### ISSUE TITLE
Logistics: Items to Create/Print

### ISSUE THREAD

**Issue by dsturgell** [atxryan/nwa-tech-summit#28]
- [x] Table tent (1: Table #, github url & Team url; 2: WIFI)

- [x] Print Azure Pass Codes

**Comment by atxryan** [comment]
link to Teams site: https://teams.microsoft.com/l/team/19%3a913ea4be6fa04051ad0baf915c43a94a%40thread.skype/conversations?groupId=d0bcf4df-3410-4d4d-a58d-c9d33111a9e3&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47

**Comment by dsturgell** [comment]
Teams Site AKA Link: https://aka.ms/NWATechTeams

**Comment by dsturgell** [comment]
Wifi: exchange-guest
PW: exchange987

**Comment by dsturgell** [comment]
Printed & ready to go
