### ISSUE TITLE
Review presentation and challenge content

### ISSUE THREAD

**Issue by aflinchb** [atxryan/nwa-tech-summit#31]
Review:

- Challenge content in md files
- Presentation content (Intro to Azure, [Intro to Cosmos DB](https://microsoft.sharepoint.com/:p:/t/WMTCSEEngagement/EblevX_DYLdDnIJ_m6PamMcBvF3tph_SCpYUqUby32wNag), Intro to AKS)

**Comment by bartr** [comment]
The content is looking great. I made some changes and submitted a PR.
